# Generated by Django 5.2.17 on 2026-09-18 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], db_index=True, max_length=16)),
                ('profile_image', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('normalized_name', models.CharField(db_index=True, max_length=220)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=24)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=24)),
                ('mobile_number', models.CharField(blank=True, max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='patient_email_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'birthdate'), name='patient_identity_uniq')],
            },
        ),
    ]
