# Generated by Django 5.2.17 on 2026-09-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=120)),
                ('doctor_name', models.CharField(max_length=120)),
                ('treatment_date', models.DateField()),
                ('tooth_numbers', models.CharField(blank=True, max_length=120)),
                ('procedure', models.CharField(max_length=120)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='unpaid', max_length=24)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_records', to='scheduling.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_records', to='accounts.patientprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'treatment_date'], name='record_patient_date_idx'), models.Index(fields=['payment_status'], name='record_payment_status_idx')],
            },
        ),
    ]
