# Generated by Django 5.2.17 on 2026-09-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('patient_phone', models.CharField(blank=True, max_length=24)),
                ('doctor_name', models.CharField(max_length=120)),
                ('service_name', models.CharField(max_length=120)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('source', models.CharField(choices=[('patient', 'Patient'), ('manual', 'Manual'), ('follow_up', 'Follow-up')], default='patient', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('booking_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.patientprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'appointment_date'], name='appt_patient_date_idx'), models.Index(fields=['doctor', 'appointment_date', 'appointment_time'], name='appt_doctor_slot_idx'), models.Index(fields=['status', 'appointment_date'], name='appt_status_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'completed', 'cancelled'])), name='appointment_status_valid'), models.CheckConstraint(condition=models.Q(('source__in', ['patient', 'manual', 'follow_up'])), name='appointment_source_valid')],
            },
        ),
    ]
